CREATE TABLE IF NOT EXISTS bosslist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  note TEXT,
  date TEXT,
  type TEXT NOT NULL,
  kills TEXT
);

INSERT INTO bosslist (name, note, date, type, kills) VALUES
('Trojan Squirrel', 'Mini Event', '02/01/2026', 'previous', '0'),
('King Slime', 'Half Week', '04/01/2026', 'previous', '0'),
('Eye of Cthulhu', NULL, '06/01/2026', 'previous', '0'),
('Desert Scourge', 'Half Week', '09/01/2026', 'previous', '0'),
('Giant Clam', 'Mini Event', '09/01/2026', 'previous', '0'),
('Eater of Worlds', NULL, NULL, 'current', '0'),
('Cursed Coffin', 'Mini Event', NULL, 'current', '0'),
('The Hive Mind', 'Half Week', NULL, 'current', '0'),
('The Perforators', 'Mini Event', NULL, 'current', '0'),
('Crabulon', 'Mini Event', NULL, 'current', '0'),
('Skeletron', NULL, NULL, 'future', '0'),
('Deerclops', 'Mini Event', NULL, 'future', '0'),
('Queen Bee', 'Half Week', NULL, 'future', '0'),
('The Slime God', NULL, NULL, 'future', '0'),
('Deviantt', 'Half Week', NULL, 'future', '0'),
('Wall of Flesh', NULL, NULL, 'future', '0'),
('Queen Slime', NULL, NULL, 'future', '0'),
('Cryogen', NULL, NULL, 'future', '0'),
('Banished Baron', 'Half Week', NULL, 'future', '0'),
('The Destroyer', NULL, NULL, 'future', '0'),
('Skeletron Prime', NULL, NULL, 'future', '0'),
('Brimstone Elemental', 'Half Week', NULL, 'future', '0'),
('The Twins', NULL, NULL, 'future', '0'),
('Aquatic Scourge', 'Half Week', NULL, 'future', '0'),
('Lifelight', NULL, NULL, 'future', '0'),
('Calamitas Clone', NULL, NULL, 'future', '0'),
('Plantera', NULL, NULL, 'future', '0'),
('Anahita & The Leviathan', 'Half Week', NULL, 'future', '0'),
('Astrum Aureus', NULL, NULL, 'future', '0'),
('Golem', NULL, NULL, 'future', '0'),
('Duke Fishron', 'Half Week', NULL, 'future', '0'),
('Ravager', NULL, NULL, 'future', '0'),
('Empress of Light', 'Half Week', NULL, 'future', '0'),
('Astrum Deus', NULL, NULL, 'future', '0'),
('Lunatic Cultist & Moon Lord', 'Longer Session', NULL, 'future', '0'),
('Profaned Guardians', NULL, NULL, 'future', '0'),
('Dragonfolly', NULL, NULL, 'future', '0'),
('Providence', NULL, NULL, 'future', '0'),
('Champion of Timber', 'Half Week', NULL, 'future', '0'),
('Champion of Terra', 'Mini Event', NULL, 'future', '0'),
('Ceaseless Void', NULL, NULL, 'future', '0'),
('Champion of Earth', 'Half Week', NULL, 'future', '0'),
('Champion of Nature', 'Mini Event', NULL, 'future', '0'),
('Storm Weaver', NULL, NULL, 'future', '0'),
('Champion of Life', 'Half Week', NULL, 'future', '0'),
('Champion of Death', 'Mini Event', NULL, 'future', '0'),
('Signus', NULL, NULL, 'future', '0'),
('Champion of Spirit', 'Half Week', NULL, 'future', '0'),
('Champion of Will', 'Mini Event', NULL, 'future', '0'),
('Polterghast', NULL, NULL, 'future', '0'),
('Old Duke', NULL, NULL, 'future', '0'),
('Devourer of Gods', NULL, NULL, 'future', '0'),
('Eridanus', NULL, NULL, 'future', '0'),
('Yharon', NULL, NULL, 'future', '0'),
('Abominationn', NULL, NULL, 'future', '0'),
('Exo Mechs', 'Longer Session', NULL, 'future', '0'),
('Supreme Calamitas', 'Longer Session', NULL, 'future', '0'),
('Mutant', 'Longer Session', NULL, 'future', '0'),
('Boss Rush', 'Longer Session', NULL, 'future', '0');