CREATE TABLE IF NOT EXISTS bosslist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  note TEXT,
  date TEXT,
  type TEXT NOT NULL
);

INSERT INTO bosslist (name, note, date, type) VALUES
('Trojan Squirrel', 'Mini Event', '02/01/2026', 'previous'),
('King Slime', 'Half Week', '04/01/2026', 'previous'),
('Eye of Cthulhu', NULL, '06/01/2026', 'previous'),
('Desert Scourge', 'Half Week', '09/01/2026', 'previous'),
('Giant Clam', 'Mini Event', '09/01/2026', 'previous'),
('Eater of Worlds', NULL, NULL, 'current'),
('Cursed Coffin', 'Mini Event', NULL, 'current'),
('Hive Mind', 'Half Week', NULL, 'future'),
('Crabulon', 'Mini Event', NULL, 'future'),
('Skeletron', NULL, NULL, 'future'),
('Deerclops', 'Mini Event', NULL, 'future'),
('Queen Bee', 'Half Week', NULL, 'future'),
('The Slime God', NULL, NULL, 'future'),
('Deviantt', 'Half Week', NULL, 'future'),
('Wall of Flesh', NULL, NULL, 'future'),
('Queen Slime', NULL, NULL, 'future'),
('Cryogen', NULL, NULL, 'future'),
('Banished Baron', 'Half Week', NULL, 'future'),
('The Destroyer', NULL, NULL, 'future'),
('Skeletron Prime', NULL, NULL, 'future'),
('Brimstone Elemental', 'Half Week', NULL, 'future'),
('The Twins', NULL, NULL, 'future'),
('Aquatic Scourge', 'Half Week', NULL, 'future'),
('Lifelight', NULL, NULL, 'future'),
('Calamitas Clone', NULL, NULL, 'future'),
('Plantera', NULL, NULL, 'future'),
('Anahita & The Leviathan', 'Half Week', NULL, 'future'),
('Astrum Aureus', NULL, NULL, 'future'),
('Golem', NULL, NULL, 'future'),
('Duke Fishron', 'Half Week', NULL, 'future'),
('Ravager', NULL, NULL, 'future'),
('Empress of Light', 'Half Week', NULL, 'future'),
('Astrum Deus', NULL, NULL, 'future'),
('Lunatic Cultist & Moon Lord', 'Longer Session', NULL, 'future'),
('Profaned Guardians', NULL, NULL, 'future'),
('Dragonfolly', NULL, NULL, 'future'),
('Providence', NULL, NULL, 'future'),
('1st 2 Champions', 'Half Week', NULL, 'future'),
('Ceaseless Void', NULL, NULL, 'future'),
('2nd 2 Champions', 'Half Week', NULL, 'future'),
('Storm Weaver', NULL, NULL, 'future'),
('3rd 2 Champions', 'Half Week', NULL, 'future'),
('Signus', NULL, NULL, 'future'),
('4th 2 Champions', 'Half Week', NULL, 'future'),
('Polterghast', NULL, NULL, 'future'),
('Old Duke', NULL, NULL, 'future'),
('Devourer of Gods', NULL, NULL, 'future'),
('Eridanus', NULL, NULL, 'future'),
('Yharon', NULL, NULL, 'future'),
('Abominationn', NULL, NULL, 'future'),
('Exo Mechs', NULL, NULL, 'future'),
('Supreme Calamitas', NULL, NULL, 'future'),
('Mutant', 'Longer Session', NULL, 'future'),
('Boss Rush', 'Longer Session', NULL, 'future');